/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.awt.Toolkit;
import logika.Kontroler;
import server.PokreniServer;

/**
 *
 * @author PC
 */
public class FormaServer extends javax.swing.JFrame {
    PokreniServer ps;

    /**
     * Creates new form FormaServer
     */
    public FormaServer() {
        initComponents();
         Toolkit tk = Toolkit.getDefaultToolkit();
        int x = (int) tk.getScreenSize().getWidth();
        int y = (int) tk.getScreenSize().getHeight();
        setSize(x, y);
        btnZaustaviServer.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPokreniServer = new javax.swing.JButton();
        txtStatus = new javax.swing.JTextField();
        btnZaustaviServer = new javax.swing.JButton();
        panelBaza = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDriver = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnPromeniDriver = new javax.swing.JButton();
        btnPromeniUsername = new javax.swing.JButton();
        btnPromeniPass = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_Url = new javax.swing.JTextField();
        btnPromeniUrl = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SERVER"));
        jPanel1.setLayout(null);

        btnPokreniServer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPokreniServer.setForeground(new java.awt.Color(102, 102, 102));
        btnPokreniServer.setText("Pokreni server");
        btnPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniServerActionPerformed(evt);
            }
        });
        jPanel1.add(btnPokreniServer);
        btnPokreniServer.setBounds(1010, 180, 160, 50);

        txtStatus.setEditable(false);
        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txtStatus);
        txtStatus.setBounds(1010, 260, 270, 50);

        btnZaustaviServer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnZaustaviServer.setForeground(new java.awt.Color(102, 102, 102));
        btnZaustaviServer.setText("Zaustavi server");
        btnZaustaviServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviServerActionPerformed(evt);
            }
        });
        jPanel1.add(btnZaustaviServer);
        btnZaustaviServer.setBounds(1010, 360, 170, 50);

        panelBaza.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Unesite driver:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Unesite username:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Unesite password:");

        txtDriver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDriver.setForeground(new java.awt.Color(102, 102, 102));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(102, 102, 102));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(102, 102, 102));

        btnPromeniDriver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPromeniDriver.setForeground(new java.awt.Color(102, 102, 102));
        btnPromeniDriver.setText("Promeni driver");
        btnPromeniDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniDriverActionPerformed(evt);
            }
        });

        btnPromeniUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPromeniUsername.setForeground(new java.awt.Color(102, 102, 102));
        btnPromeniUsername.setText("Promeni username");
        btnPromeniUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniUsernameActionPerformed(evt);
            }
        });

        btnPromeniPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPromeniPass.setForeground(new java.awt.Color(102, 102, 102));
        btnPromeniPass.setText("Promeni password");
        btnPromeniPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniPassActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Unesite url:");

        txt_Url.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Url.setForeground(new java.awt.Color(102, 102, 102));

        btnPromeniUrl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPromeniUrl.setForeground(new java.awt.Color(102, 102, 102));
        btnPromeniUrl.setText("Promenite url");
        btnPromeniUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniUrlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBazaLayout = new javax.swing.GroupLayout(panelBaza);
        panelBaza.setLayout(panelBazaLayout);
        panelBazaLayout.setHorizontalGroup(
            panelBazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBazaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelBazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(panelBazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Url, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtPassword)
                    .addComponent(txtUsername)
                    .addComponent(txtDriver))
                .addGap(18, 18, 18)
                .addGroup(panelBazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPromeniDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPromeniUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPromeniPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPromeniUrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        panelBazaLayout.setVerticalGroup(
            panelBazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBazaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelBazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPromeniDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnPromeniUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelBazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBazaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3))
                    .addGroup(panelBazaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnPromeniPass, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBazaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelBazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(btnPromeniUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBazaLayout.createSequentialGroup()
                        .addComponent(txt_Url, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(101, 101, 101))
        );

        jPanel1.add(panelBaza);
        panelBaza.setBounds(300, 140, 640, 360);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Mladenovic_Marija_42014\\MojaAplikacijaKlijentt\\src\\images\\s1.jpg")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 20, 1600, 910);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1615, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniServerActionPerformed
        // TODO add your handling code here:
        panelBaza.setVisible(false);
        ps = new PokreniServer(this);
        ps.start();
        
        
    }//GEN-LAST:event_btnPokreniServerActionPerformed

    private void btnZaustaviServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviServerActionPerformed
        // TODO add your handling code here:
       
        ps.interrupt();
        panelBaza.setVisible(true);
    }//GEN-LAST:event_btnZaustaviServerActionPerformed

    private void btnPromeniUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniUsernameActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        Kontroler.getInstance().promeniUsername(username);
    }//GEN-LAST:event_btnPromeniUsernameActionPerformed

    private void btnPromeniDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniDriverActionPerformed
        // TODO add your handling code here:
        String driver = txtDriver.getText();
        Kontroler.getInstance().promeniDriver(driver);
    }//GEN-LAST:event_btnPromeniDriverActionPerformed

    private void btnPromeniPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniPassActionPerformed
        // TODO add your handling code here:
        String pass = txtPassword.getText();
        Kontroler.getInstance().promeniPass(pass);
    }//GEN-LAST:event_btnPromeniPassActionPerformed

    private void btnPromeniUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniUrlActionPerformed
        // TODO add your handling code here:
        String url = txt_Url.getText();
        Kontroler.getInstance().promeniUrl(url);
    }//GEN-LAST:event_btnPromeniUrlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreniServer;
    private javax.swing.JButton btnPromeniDriver;
    private javax.swing.JButton btnPromeniPass;
    private javax.swing.JButton btnPromeniUrl;
    private javax.swing.JButton btnPromeniUsername;
    private javax.swing.JButton btnZaustaviServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBaza;
    private javax.swing.JTextField txtDriver;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txt_Url;
    // End of variables declaration//GEN-END:variables

    public void serverPokrenut() {
        txtStatus.setText("Server je pokrenut!");
        btnPokreniServer.setEnabled(false);
        btnZaustaviServer.setEnabled(true);
    }

    public void serverNijePokrenut() {
        txtStatus.setText("Server nije pokrenut!");
        btnPokreniServer.setEnabled(true);
        btnZaustaviServer.setEnabled(false);
    }
}
